### ISSUE TITLE
Pull node version from .nvmrc

### ISSUE THREAD

**Issue by jaythomas** [jackadamson/onitama#1]
For those not using docker, it would be nice to have a `.nvmrc` file that gets picked up by [fnm](https://github.com/Schniz/fnm)/[nvm](https://github.com/nvm-sh/nvm) so the app can run locally and ensure I'm developing with a compatible version of node. Likewise, the Dockerfile which currently has a node version hardcoded could instead use the `.nvmrc` file too along with fnm to automatically install the correct version of node during container setup.

**Comment by jackadamson** [comment]
That's a good point, I've added an `.nvmrc` and changed the Dockerfiles to use fnm as suggested.  
I hadn't heard of fnm before, but seems to work well!  
Thanks for the suggestion
