### ISSUE TITLE
Sensei's Path Expansion

### ISSUE THREAD

**Issue by Fu14n0** [jackadamson/onitama#12]
Hello, your website has been a great training tool for me and and also an efficient way to play matches with distant friends. As a lover of this game I would like to ask if there are any plans to add the cards present in the sensei path expansion.

![imagem_2022-09-15_092117104](https://user-images.githubusercontent.com/113604008/190402230-d90b85c1-a0a5-4429-b453-fdc3b67997be.png)

Promo Cards:
![pic3718352](https://user-images.githubusercontent.com/113604008/190403530-130dae75-1940-40b1-8d80-fefbdfee5e68.png)

Currently don't know of any other way to play the expansion with friends without a physical version of this game so I believe it would be a great addition.

Thank you very much for your work.

**Comment by jackadamson** [comment]
I really like this change and will try to get them merged over the next week or so!

Apologies for the slow turnaround, GitHub has stopped notifying me via the app

**Comment by onitamasuperfan** [comment]
It looks like these changes have been rolled back on the onitama.app website. Any idea when they'll return?

**Comment by onitamasuperfan** [comment]
Assuming you haven't abandoned this project @jackadamson @jack5thdomain, when you do re-add Sensei's Path it would be nice to have the option to turn it on/off. 

So you could run the game with the following options:

1.  Just the Base Game
2.  Just Sensei's Path
3. The Base Game + Sensei's Path
4. All the cards, including promos

It would also be good to be able to turn individual promos or even cards on or off.

**Comment by jackadamson** [comment]
I don't believe I've reverted any changes in the past 6 months, perhaps check if you see the changes in Incognito?

It might be an issue with the service worker caching the page.

**Comment by jackadamson** [comment]
I'm hoping to add some of the expansions as toggled options in the near future, but haven't had much spare time lately.

**Comment by onitamasuperfan** [comment]
> I don't believe I've reverted any changes in the past 6 months, perhaps check if you see the changes in Incognito?
> 
> It might be an issue with the service worker caching the page.

I've just ran through some troubleshooting and every way I've tried I get just the original cards with the old all green colors. 

![image](https://github.com/jackadamson/onitama/assets/138399070/b6f2e828-fc55-4860-9a07-58cb0121679a)

Sensei's Path and the Goat/Sheep were working fine until I posted that message 2 weeks ago.

**Comment by jackadamson** [comment]
You are entirely correct, I must have somehow triggered a build of an older docker build and overwritten latest.

Now should be back Sensei's path, Promotional Cards, the non-wind cards from Way of the Wind and a new settings menu to toggle decks on and off!
