### ISSUE TITLE
Add promotional cards Lobster, Steer, Hornet, Centipede

### ISSUE THREAD

**Issue by onitamasuperfan** [jackadamson/onitama#18]
![Hornet and Centipede](https://github.com/jackadamson/onitama/assets/138399070/7126db96-cde9-417f-afd9-79af4d1d8774)
![Steer and Lobster](https://github.com/jackadamson/onitama/assets/138399070/b0d50d98-b3e2-4590-be12-40fdc514848e)

**Comment by onitamasuperfan** [comment]
@jackadamson I went ahead and added the code for these promos since it was quite simple. You said in another issue that GitHub wasn't notifying you, so I'm just tagging you so you get a ping. I hope that's ok/useful.

Thanks for all your work!

**Comment by jackadamson** [comment]
Thanks for submitting this! This should hopefully be live later tonight (but you'll need to refresh and possibly close all tabs of onitama.app to get it).
