### ISSUE TITLE
Rematch doesn't clear last move arrow from the board

### ISSUE THREAD

**Issue by jdm** [jackadamson/onitama#2]
I lost my first match and chose to start a rematch. The board looked like this:
<img width="337" alt="Screen Shot 2021-07-16 at 11 21 56 PM" src="https://user-images.githubusercontent.com/27658/126023914-8d0e0975-220f-4ea6-b0c9-bbb9c5212e87.png">

**Comment by jackadamson** [comment]
Good catch. When I changed the AI from server-side to client-side I forgot to update the reset logic.
