### ISSUE TITLE
Hornet card is incorrect

### ISSUE THREAD

**Issue by Nicko98** [jackadamson/onitama#24]
Hi,

thanks for the nice implementation of Onitama!

I noticed, that the hornet is not symmetrical to the centipede. I looked it up on BGG and found that it indeed should be symmetrical to the centipede.

Another thing:
I always win against the easy ai while almost never winning against the medium ai. I don’t know, how the difficulty is implemented, but maybe it’s easy to add a difficulty between those?

**Comment by onitamasuperfan** [comment]
Hi Nicko! 

Thanks for catching the error on Hornet. I submitted a pull request to fix it. @jackadamson works on this in his spare time but he should get to it sooner or later.

**Comment by Nicko98** [comment]
Thanks @onitamasuperfan !
I’m totally aware, that this is a spare time project. I would have submitted a PR myself, but didn‘t understand the project structure, so I thought it would probably take somebody already involved ~1min, while it would take me at least half an hour.

**Comment by jackadamson** [comment]
Definitely happy to take a look at fixing the hornet and the open PRs but can't promise they'll be very soon.

**Comment by jackadamson** [comment]
Regarding different AIs, the 3 AIs are actually just different algorithms. I wrote a bunch of different bots, played them against each other to work out rough difficulty, then picked the 3 that are most fun to play against.

Something to note about difficulty is that each bot is given 2 seconds to work out it's best move, which means that different browsers and devices get different difficulties.

So playing on a desktop, vs phone makes a reasonable difference to difficulty.

Fun fact, Android Firefox has the highest winrate of player vs Hard difficulty.

**Comment by Nicko98** [comment]
Thanks for the info on the difficulty! I thought maybe they are the same algorithm with different time limits or similar, where adding a new difficulty would be very easy.

Yesterday I got my Onitama board out and constantly copied the game state between the board and the website. And this way I had a better overview and won 2 out of 3 games and the lost one was close. Guess I just have to get used to the UI.

Thanks for your effort!
