### ISSUE TITLE
Mobile: middle card face the wrong way

### ISSUE THREAD

**Issue by Electronicks** [jackadamson/onitama#6]
Hello.

First of all, thank you for this beautiful little app. I love playing it againsta  bot on occasion and it's great to show a friend with the local multiplayer.

I found this issue on mobile (aka, when the screen size is too small to have the middle card beside the board). In this case, the middle card is placed in the opponent's zone but still in the opponent's orientation. This messes me up often because I have to rotate the card in my head to find out what my hand will be next round. I was able to test this on desktop just by icreasing the zoom level until the layout changes, you can see the middle card flip from my own orientation to the opponent's. 
![desktopOK](https://user-images.githubusercontent.com/2488182/152060136-a09ec8de-64da-49f8-805a-e907ba210e47.jpg)
![mobileNOK](https://user-images.githubusercontent.com/2488182/152060165-bdb0a966-1e1a-4c7f-9309-6660ef99cc04.jpg)

I highly suspect the coding to put the card in the opponent's orientation when it is in the opponent's zone. So I see two ways to fix the issue.

A: Code a way to flip the middle card in the opponent's zone
   OR
B: Move the middle card to the player's zone and identify it as unusable for this turn (greyed out?).

I have zero experience in the languages used in this repo, so I apologize for not offering a pull request instead of an issue ticket. Hopefully it is a simple fix for you. Cheers!

**Comment by jackadamson** [comment]
Very good point, that does look really confusing.

I've chosen to go with A, and have flipped it in the opponents zone, and have also added a caption to show it's been played

![image](https://user-images.githubusercontent.com/7891953/161721231-0c78f52d-ddcb-4deb-a8be-5df68caa7a84.png)

Thanks for pointing this out :grin:

**Comment by Electronicks** [comment]
Looks great. Thank you, my friend!
